# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170427_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_source',
            field=models.URLField(default=''),
        ),
    ]
